
development:
  adapter: postgresql
  encoding: unicode
  database: web_dev_bookmarks_dev
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: web_dev_bookmarks_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: web_dev_bookmarks_prod
  pool: 5
  password:
